### PR TITLE
feat : Added YouTube link in the movie's landing page for its trailer…

### PR DESCRIPTION
**Pull request by talatam143**
Hello @praveenpuglia ,

I have developed the trailer component in the movie page and changed the Mongo DB database to TMDB api

### CODE REVIEW

**Comment by praveenpuglia** [comment]
Why these many changes?

**Comment by talatam143** [comment]
Hi @praveenpuglia ,
As the database changed i have removed the dashboard component which uses MongoDB database. While we are using TMDB API we have to refactor whole movies component from starting and have included error handing. Changed the state management to Redux from Context API as  the state handling became complex

**Comment by praveenpuglia** [comment]
Right. See, the redux changes aren't related to your db change or your css changes for some of the components. We shouldn't send everything in PRs.

The number 1 rule of good PRs is to only keep related changes.  That way, if some bug is found in production and we have to go back to a previous version, we can rollback the exact change instead of all the other changes. 

Can you update your PR to only include #1 related changes?

**Comment by talatam143** [comment]
@praveenpuglia 
Sure Praveen i will keep the changes with respect to our feature only.

**Pull request closed without merging**
